### ISSUE TITLE
ImportError: dlopen(sharpy-sc2/sc2pathlibp/sc2pathlib.so, 2): no suitable image found. 

### ISSUE THREAD

**Issue by mikhailsidorov** [DrInfy/sharpy-starter-bot#1]
Hello. 

During the execution of the command `python run_custom.py -m GoldenWallLE -p1 terranbot -p2 ai`, the following error occurs:

`ImportError: dlopen(sharpy-sc2/sc2pathlibp/sc2pathlib.so, 2): no suitable image found.  Did find:
	sharpy-sc2/sc2pathlibp/sc2pathlib.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
	/Users/mikhailsidorov/dev/my/sharpy-starter-bot/sharpy-sc2/sc2pathlibp/sc2pathlib.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00`
	
**OS:** Mac OS Big Sur 11.2

**Python version:** Python 3.7.8

**Steps to reproduce:**

`git clone --recursive https://github.com/DrInfy/sharpy-starter-bot`
` cd sharpy-starter-bot`
` python3.7 -m venv venv`
` source venv/bin/activate`
` pip install -r requirements.txt`
` cd sharpy-sc2`
` pip install -r requirements.txt`
` cd sharpy-sc2/python-sc2`
` pipenv install`
` python run_custom.py -m GoldenWallLE -p1 terranbot -p2 ai`

**Full traceback:**

`Traceback (most recent call last):`
`  File "run_custom.py", line 4, in <module>`
`    from protossbot.bot import ProtossBot`
`  File "/Users/mikhailsidorov/dev/my/sharpy-starter-bot/protossbot/bot.py", line 5, in <module>`
`    from sharpy.knowledges import KnowledgeBot`
`  File "sharpy-sc2/sharpy/knowledges/__init__.py", line 1, in <module>`
`    from .knowledge import Knowledge`
`  File "sharpy-sc2/sharpy/knowledges/knowledge.py", line 9, in <module>`
`    from sharpy.managers.core import *`
`  File "sharpy-sc2/sharpy/managers/__init__.py", line 1, in <module>`
`    from sharpy.managers.core.manager_base import ManagerBase`
`  File "sharpy-sc2/sharpy/managers/core/__init__.py", line 8, in <module>`
`    from .zone_manager import ZoneManager`
`  File "sharpy-sc2/sharpy/managers/core/zone_manager.py", line 5, in <module>`
`    import sc2pathlibp`
`  File "sharpy-sc2/sc2pathlibp/__init__.py", line 1, in <module>`
`    from .path_finder import PathFinder`
`  File "sharpy-sc2/sc2pathlibp/path_finder.py", line 1, in <module>`
`    from .sc2pathlib import PathFind`
`ImportError: dlopen(sharpy-sc2/sc2pathlibp/sc2pathlib.so, 2): no suitable image found.  Did find:`
`	sharpy-sc2/sc2pathlibp/sc2pathlib.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00`
`	/Users/mikhailsidorov/dev/my/sharpy-starter-bot/sharpy-sc2/sc2pathlibp/sc2pathlib.so: unknown file type, first eight `bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00`

**Comment by DrInfy** [comment]
Unfortunately I have not been able to figure out how to support both mac and linux at the same time because the use the same file and I can't build it for mac either.

Here's instruction for building pathlib for mac: [Building pathlib](https://github.com/DrInfy/sc2-pathlib#installing).

**Comment by mikhailsidorov** [comment]
Thanks. I will try it and come back.
